/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package about_Program;
import about_Us.*;
import pboparkir.Welkom;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class AboutProgram extends javax.swing.JFrame {

    /**
     * Creates new form AboutUs
     */
    public AboutProgram() {
        initComponents();
        background.setBackground(new Color(0,0,0,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(588, 423));
        jPanel1.setLayout(null);

        background.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1);
        jButton1.setBounds(461, 324, 69, 25);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 47)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bismillahtubes/Bahan/logo - Copy (2).png"))); // NOI18N
        jLabel22.setText("P   RKING");
        background.add(jLabel22);
        jLabel22.setBounds(20, 150, 440, 94);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bismillahtubes/Bahan/mobilcilik.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        background.add(jLabel2);
        jLabel2.setBounds(230, 180, 40, 40);

        jLabel3.setText("UMM PARKING");
        background.add(jLabel3);
        jLabel3.setBounds(240, 10, 90, 14);

        jLabel4.setText("\tUMM Parking adalah sebuah aplikasi yang memudahkan agar mahasiswa maupun");
        background.add(jLabel4);
        jLabel4.setBounds(70, 40, 490, 14);

        jLabel5.setText("dosen dapat mengetahui parkiran mana yang masih  tersisa serta memudahkan mahasiswa ");
        background.add(jLabel5);
        jLabel5.setBounds(20, 60, 550, 14);

        jLabel6.setText("dan dosen mengingat dimana le- tak kendaraan yang telah diparkir sebelumnya. UMM Park-");
        background.add(jLabel6);
        jLabel6.setBounds(20, 80, 570, 14);

        jLabel7.setText("ing ini meminimalisir adanya tukang parkir karena menggunakan sistem penginputan nopol");
        background.add(jLabel7);
        jLabel7.setBounds(20, 100, 590, 14);

        jLabel8.setText("dan kode unik sebagai pengaman unik agar pemilik  kendaraan dapat keluar.");
        background.add(jLabel8);
        jLabel8.setBounds(20, 120, 460, 14);

        jPanel1.add(background);
        background.setBounds(20, 20, 550, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_Us/Background-kapoci.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(588, 423));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 588, 434);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Welkom home = new Welkom();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
